
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author reese
 */
public class AddAccountMenu extends javax.swing.JDialog
{

    private Bank bank;
    private Customer customer;

    /**
     * Creates new form AddAccountMenu
     */
    public AddAccountMenu(java.awt.Frame parent, boolean modal, Bank bank)
    {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.bank = bank;
        customer = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        ssnLabel = new javax.swing.JLabel();
        ssnTextField = new javax.swing.JTextField();
        initialDepositLabel = new javax.swing.JLabel();
        initialDepositTextField = new javax.swing.JTextField();
        accountTypeLabel = new javax.swing.JLabel();
        accountTypeComboBox = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Account Menu");
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        firstNameLabel.setText("First Name:");
        getContentPane().add(firstNameLabel);

        firstNameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(firstNameTextField);

        lastNameLabel.setText("Last Name:");
        getContentPane().add(lastNameLabel);
        getContentPane().add(lastNameTextField);

        ssnLabel.setText("Social Security Number:");
        getContentPane().add(ssnLabel);

        ssnTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ssnTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ssnTextField);

        initialDepositLabel.setText("Initial Deposit");
        getContentPane().add(initialDepositLabel);
        getContentPane().add(initialDepositTextField);

        accountTypeLabel.setText("Account Type");
        getContentPane().add(accountTypeLabel);

        accountTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking", "Savings" }));
        accountTypeComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                accountTypeComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(accountTypeComboBox);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_accountTypeComboBoxActionPerformed
    {//GEN-HEADEREND:event_accountTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountTypeComboBoxActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_firstNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
    {//GEN-HEADEREND:event_okButtonActionPerformed
        double amount = 0;
        String firstName = firstNameTextField.getText();
        String lastName = lastNameTextField.getText();
        String ssn = ssnTextField.getText();
        Account account = null;
        if (firstNameTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "First name must not be empty.", "Input Error", JOptionPane.WARNING_MESSAGE);

        } else if (lastNameTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Last name must not be empty.", "Input Error", JOptionPane.WARNING_MESSAGE);
        } else if (ssnTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "SSN must not be empty.", "Input Error", JOptionPane.WARNING_MESSAGE);
        } else if (!ssnTextField.getText().matches("(?!000|666)[0-8][0-9]{2}-(?!00)[0-9]{2}-(?!0000)[0-9]{4}"))
        {
            JOptionPane.showMessageDialog(this, "SSN must be in xxx-xx-xxxx format.", "Input Error", JOptionPane.WARNING_MESSAGE);
        } else if (initialDepositTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Initial deposit must be entered.", "Input Error", JOptionPane.WARNING_MESSAGE);
        } else
        {
            try
            {
                amount = Bank.round(Double.parseDouble(initialDepositTextField.getText()), 2);
            } catch (NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(this, "Initial deposit must be a number.");
            }
            if (accountTypeComboBox.getSelectedItem().toString() == "Checking")
            {
                if (amount >= 100)
                {
                    account = new Checking(amount);
                } else
                {
                    JOptionPane.showMessageDialog(this, "Initial deposit must be at least $100 for Checking accounts.");
                }
            } else if (accountTypeComboBox.getSelectedItem().toString() == "Savings")
            {
                if (amount >= 50)
                {
                    account = new Savings(amount);
                } else
                {
                    JOptionPane.showMessageDialog(this, "Initial deposit must be at least $50 for Savings accounts.");
                }
            }
        }
        if (account != null)
        {
            customer = new Customer(firstName, lastName, ssn, account);
            bank.addCustomer(customer);
            this.dispose();
        }
        //create an account
    }//GEN-LAST:event_okButtonActionPerformed

    private void ssnTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ssnTextFieldActionPerformed
    {//GEN-HEADEREND:event_ssnTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accountTypeComboBox;
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel initialDepositLabel;
    private javax.swing.JTextField initialDepositTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JTextField ssnTextField;
    // End of variables declaration//GEN-END:variables

    Customer getCustomer()
    {
        return customer;
    }
}
